services:
  test_clickhouse:
    image: clickhouse:25.9
    logging:
      driver: none
    ports:
      - "10123:8123"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
